### ISSUE TITLE
A pasta Metadata deve ser excluída. 

### ISSUE THREAD

**Issue by rodrigofujioka** [JhonyCosmo/exercicio-jsf-crud#2]
A pasta metadata deve ser colocada no ignore do git, ela traz informações de configuração e plugins do eclipse, ou seja, não é pertinente ao projeto.   Ela deve ser excluída do git, na sua máquina local ela pode permancer.

**Comment by JhonyCosmo** [comment]
Realizado

**Comment by JhonyCosmo** [comment]
Realizado
